"""
This type stub file was generated by pyright.
"""

from typing import Optional
from pydantic import BaseModel, model_validator

class SearchGoogleAction(BaseModel):
	query: str
	...


class GoToUrlAction(BaseModel):
	url: str
	...


class ClickElementAction(BaseModel):
	index: int
	xpath: Optional[str] = ...


class InputTextAction(BaseModel):
	index: int
	text: str
	xpath: Optional[str] = ...


class DoneAction(BaseModel):
	text: str
	success: bool
	...


class SwitchTabAction(BaseModel):
	page_id: int
	...


class OpenTabAction(BaseModel):
	url: str
	...


class ScrollAction(BaseModel):
	amount: Optional[int] = ...


class SendKeysAction(BaseModel):
	keys: str
	...


class ExtractPageContentAction(BaseModel):
	value: str
	...


class NoParamsAction(BaseModel):
	"""
	Accepts absolutely anything in the incoming data
	and discards it, so the final parsed model is empty.
	"""
	@model_validator(mode='before')
	def ignore_all_inputs(cls, values): # -> dict[Any, Any]:
		...
	
	class Config:
		extra = ...
	
	


