"""
This type stub file was generated by pyright.
"""

from typing import Callable, Dict, Type
from pydantic import BaseModel

class RegisteredAction(BaseModel):
	"""Model for a registered action"""
	name: str
	description: str
	function: Callable
	param_model: Type[BaseModel]
	model_config = ...
	def prompt_description(self) -> str:
		"""Get a description of the action for the prompt"""
		...
	


class ActionModel(BaseModel):
	"""Base model for dynamically created action models"""
	model_config = ...
	def get_index(self) -> int | None:
		"""Get the index of the action"""
		...
	
	def set_index(self, index: int): # -> None:
		"""Overwrite the index of the action"""
		...
	


class ActionRegistry(BaseModel):
	"""Model representing the action registry"""
	actions: Dict[str, RegisteredAction] = ...
	def get_prompt_description(self) -> str:
		"""Get a description of all actions for the prompt"""
		...
	


