[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock

[program:filebrowser]
command=/opt/filebrowser/filebrowser
directory=/opt/filebrowser
autostart=true
autorestart=true
stdout_logfile=/var/log/filebrowser.log
stderr_logfile=/var/log/filebrowser_err.log

[program:comfyui]
command=/root/comfy/ComfyUI/service.sh
directory=/root/comfy/ComfyUI
autostart=true
autorestart=true
stdout_logfile=/var/log/comfyui.log
stderr_logfile=/var/log/comfyui_err.log
