"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from langchain_core.messages import BaseMessage

logger = ...
def extract_json_from_model_output(content: str) -> dict:
	"""Extract JSON from model output, handling both plain JSON and code-block-wrapped JSON."""
	...

def convert_input_messages(input_messages: list[BaseMessage], model_name: Optional[str]) -> list[BaseMessage]:
	"""Convert input messages to a format that is compatible with the planner model"""
	...

def save_conversation(input_messages: list[BaseMessage], response: Any, target: str, encoding: Optional[str] = ...) -> None:
	"""Save conversation history to file."""
	...

