"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional
from pydantic import BaseModel

@dataclass
class HashedDomElement:
	"""
	Hash of the dom element to be used as a unique identifier
	"""
	branch_path_hash: str
	attributes_hash: str
	xpath_hash: str
	...


class Coordinates(BaseModel):
	x: int
	y: int
	...


class CoordinateSet(BaseModel):
	top_left: Coordinates
	top_right: Coordinates
	bottom_left: Coordinates
	bottom_right: Coordinates
	center: Coordinates
	width: int
	height: int
	...


class ViewportInfo(BaseModel):
	scroll_x: int
	scroll_y: int
	width: int
	height: int
	...


@dataclass
class DOMHistoryElement:
	tag_name: str
	xpath: str
	highlight_index: Optional[int]
	entire_parent_branch_path: list[str]
	attributes: dict[str, str]
	shadow_root: bool = ...
	css_selector: Optional[str] = ...
	page_coordinates: Optional[CoordinateSet] = ...
	viewport_coordinates: Optional[CoordinateSet] = ...
	viewport_info: Optional[ViewportInfo] = ...
	def to_dict(self) -> dict:
		...
	


