"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Coroutine, ParamSpec, TypeVar

logger = ...
R = TypeVar('R')
P = ParamSpec('P')
def time_execution_sync(additional_text: str = ...) -> Callable[[Callable[P, R]], Callable[P, R]]:
	...

def time_execution_async(additional_text: str = ...) -> Callable[[Callable[P, Coroutine[Any, Any, R]]], Callable[P, Coroutine[Any, Any, R]]]:
	...

def singleton(cls): # -> Callable[..., Any]:
	...

