"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import TYPE_CHECKING
from playwright.async_api import Page
from browser_use.dom.views import DOMState
from browser_use.utils import time_execution_async

if TYPE_CHECKING:
	...
logger = ...
@dataclass
class ViewportInfo:
	width: int
	height: int
	...


class DomService:
	def __init__(self, page: Page) -> None:
		...
	
	@time_execution_async('--get_clickable_elements')
	async def get_clickable_elements(self, highlight_elements: bool = ..., focus_element: int = ..., viewport_expansion: int = ...) -> DOMState:
		...
	


