"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from browser_use.agent.views import AgentHistoryList

if TYPE_CHECKING:
	...
logger = ...
def create_history_gif(task: str, history: AgentHistoryList, output_path: str = ..., duration: int = ..., show_goals: bool = ..., show_task: bool = ..., show_logo: bool = ..., font_size: int = ..., title_font_size: int = ..., goal_font_size: int = ..., margin: int = ..., line_spacing: float = ...) -> None:
	"""Create a GIF from the agent's history with overlaid task and goal text."""
	...

