"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, TYPE_CHECKING
from langchain_core.messages import HumanMessage, SystemMessage
from browser_use.agent.views import ActionResult, AgentStepInfo
from browser_use.browser.views import BrowserState

if TYPE_CHECKING:
	...
class SystemPrompt:
	def __init__(self, action_description: str, max_actions_per_step: int = ...) -> None:
		...
	
	def get_system_message(self) -> SystemMessage:
		"""
		Get the system prompt for the agent.

		Returns:
		    SystemMessage: Formatted system prompt
		"""
		...
	


class AgentMessagePrompt:
	def __init__(self, state: BrowserState, result: Optional[List[ActionResult]] = ..., include_attributes: list[str] = ..., step_info: Optional[AgentStepInfo] = ...) -> None:
		...
	
	def get_user_message(self, use_vision: bool = ...) -> HumanMessage:
		...
	


class PlannerPrompt(SystemPrompt):
	def get_system_message(self) -> SystemMessage:
		...
	


