"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Optional
from pydantic import BaseModel
from browser_use.dom.history_tree_processor.service import DOMHistoryElement
from browser_use.dom.views import DOMState

class TabInfo(BaseModel):
	"""Represents information about a browser tab"""
	page_id: int
	url: str
	title: str
	...


@dataclass
class BrowserState(DOMState):
	url: str
	title: str
	tabs: list[TabInfo]
	screenshot: Optional[str] = ...
	pixels_above: int = ...
	pixels_below: int = ...
	browser_errors: list[str] = ...


@dataclass
class BrowserStateHistory:
	url: str
	title: str
	tabs: list[TabInfo]
	interacted_element: list[DOMHistoryElement | None] | list[None]
	screenshot: Optional[str] = ...
	def to_dict(self) -> dict[str, Any]:
		...
	


class BrowserError(Exception):
	"""Base class for all browser errors"""
	...


class URLNotAllowedError(BrowserError):
	"""Error raised when a URL is not allowed"""
	...


